import { AppProps } from 'next/app';
import AppState from '../context/AppState';
import Head from 'next/head';
import '../styles/globals.scss';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Pomodoro App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AppState>
        <Component {...pageProps} />
      </AppState>
    </>
  );
}

export default MyApp;
