import { useState } from 'react';
import { SelectOption } from '../utils/types';
import Image from 'next/image';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Selector from '../components/Selector';
import Timer from '../components/Timer';
import SettingsModal from '../components/modals/SettingsModal';

export default function Home() {
  const [selected, setSelected] = useState<SelectOption>('pomodoro');
  const [minutes, setMinutes] = useState<number | string>('00');
  const [seconds, setSeconds] = useState<number | string>('00');
  const [isPaused, setIsPaused] = useState(true);
  const [settingsHidden, setSettingsHidden] = useState(true);

  return (
    <div
      className={
        !settingsHidden
          ? `${styles.container} ${styles.settings}`
          : styles.container
      }
    >
      <Head>
        <title>Pomodoro App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* SettingsModal is HIDDEN unless !settingsHidden */}
      {!settingsHidden ? (
        <SettingsModal setSettingsHidden={setSettingsHidden} />
      ) : (
        ''
      )}

      {/* Logo */}
      <h1 className={styles.logo}>pomodoro</h1>
      {/* Select Bar */}
      <Selector selected={selected} setSelected={setSelected} />
      {/* Timer Section */}
      <Timer
        minutes={minutes}
        seconds={seconds}
        isPaused={isPaused}
        setIsPaused={setIsPaused}
      />
      {/* Settings Button */}
      <div
        className={styles['settings-icon']}
        onClick={() => setSettingsHidden(false)}
      >
        <Image
          src='/assets/icon-settings.svg'
          alt='settings'
          width={30}
          height={30}
        />
      </div>
    </div>
  );
}
